### ISSUE TITLE
Environment variables: typo?

### ISSUE THREAD

**Issue by pwin** [puzzle/openshift-graphviz-cartridge#1]
<%= "#{ENV['LD_LIRARY_PATH']}:#{ENV['OPENSHIFT_GRAPHVIZ_DIR']}/usr/lib64" %>

?typo
shouldn't it be
<%= "#{ENV['LD_LIBRARY_PATH']}:#{ENV['OPENSHIFT_GRAPHVIZ_DIR']}/usr/lib64" %>

**Comment by dtschan** [comment]
This was indeed a typo. Thank you for reporting it. Fixed in d88c548.
